import type { CompanyListItem } from './companies'
import type { PageResponse } from './projects'

// TODO: remove flag to ship
export const USE_COMPANY_MOCKS = true

export const MOCK_COMPANIES: CompanyListItem[] = [
  {
    id: 1,
    legalName: 'Empresa Tech Solutions LTDA',
    socialName: 'Tech Solutions',
    description: 'Consultoria em tecnologia e transformação digital',
    logoUrl: 'https://picsum.photos/seed/company1/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 2,
    legalName: 'Grupo Inovação S.A.',
    socialName: 'Inovação',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company2/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 3,
    legalName: 'Sustentabilidade Ambiental LTDA',
    socialName: null,
    description: 'Soluções sustentáveis para empresas',
    logoUrl: null,
    city: 'Belo Horizonte',
    state: 'MG',
  },
  {
    id: 4,
    legalName: 'Educação Digital Tecnologia LTDA',
    socialName: 'EduTech',
    description: 'Plataformas educacionais e treinamento corporativo',
    logoUrl: 'https://picsum.photos/seed/company4/64/64',
    city: 'Curitiba',
    state: 'PR',
  },
  {
    id: 5,
    legalName: 'Saúde Premium Consultoria S.A.',
    socialName: 'Premium Health',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company5/64/64',
    city: null,
    state: null,
  },
  {
    id: 6,
    legalName: 'Logística Global LTDA',
    socialName: 'LogGlobal',
    description: 'Serviços de logística e distribuição',
    logoUrl: null,
    city: 'Porto Alegre',
    state: 'RS',
  },
  {
    id: 7,
    legalName: 'Energia Renovável Brasil S.A.',
    socialName: null,
    description: 'Projetos de energia solar e eólica',
    logoUrl: 'https://picsum.photos/seed/company7/64/64',
    city: 'Salvador',
    state: 'BA',
  },
  {
    id: 8,
    legalName: 'Comunicação Estratégica LTDA',
    socialName: 'CommEstr',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company8/64/64',
    city: 'Brasília',
    state: 'DF',
  },
  {
    id: 9,
    legalName: 'Manufatura Inteligente LTDA',
    socialName: 'SmartMfg',
    description: 'Automação industrial e indústria 4.0',
    logoUrl: 'https://picsum.photos/seed/company9/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 10,
    legalName: 'Finanças e Investimentos S.A.',
    socialName: null,
    description: 'Gestão de portfólio e consultoria financeira',
    logoUrl: null,
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 11,
    legalName: 'Turismo Experiencial LTDA',
    socialName: 'TurExp',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company11/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 12,
    legalName: 'Agronegócio Premium S.A.',
    socialName: 'AgroPrem',
    description: 'Tecnologia agrícola e consultoria rural',
    logoUrl: 'https://picsum.photos/seed/company12/64/64',
    city: null,
    state: 'GO',
  },
  {
    id: 13,
    legalName: 'Gastronomia Gourmet LTDA',
    socialName: null,
    description: null,
    logoUrl: null,
    city: 'Recife',
    state: 'PE',
  },
  {
    id: 14,
    legalName: 'Serviços de Limpeza Profissional LTDA',
    socialName: 'Clean Pro',
    description: 'Limpeza e higienização para corporações',
    logoUrl: 'https://picsum.photos/seed/company14/64/64',
    city: 'Fortaleza',
    state: 'CE',
  },
  {
    id: 15,
    legalName: 'Consultoria RH e Talentos S.A.',
    socialName: 'TalentHub',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company15/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 16,
    legalName: 'Segurança Eletrônica Avançada LTDA',
    socialName: null,
    description: 'Sistemas de vigilância e monitoramento',
    logoUrl: null,
    city: 'Campinas',
    state: 'SP',
  },
  {
    id: 17,
    legalName: 'Imóveis e Desenvolvimento LTDA',
    socialName: 'DevImóvel',
    description: 'Projetos residenciais e comerciais',
    logoUrl: 'https://picsum.photos/seed/company17/64/64',
    city: 'Belo Horizonte',
    state: 'MG',
  },
  {
    id: 18,
    legalName: 'Vestuário Fashion LTDA',
    socialName: 'Fashion Nova',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company18/64/64',
    city: null,
    state: null,
  },
  {
    id: 19,
    legalName: 'Bebidas Premium S.A.',
    socialName: null,
    description: 'Produção e distribuição de bebidas',
    logoUrl: null,
    city: 'Mogi Guaçu',
    state: 'SP',
  },
  {
    id: 20,
    legalName: 'Transportes e Fretes LTDA',
    socialName: 'TransFrete',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company20/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 21,
    legalName: 'Óptica e Oftalmologia Moderna LTDA',
    socialName: 'VisionCare',
    description: 'Serviços oftalmológicos e óptica',
    logoUrl: 'https://picsum.photos/seed/company21/64/64',
    city: 'Brasília',
    state: 'DF',
  },
  {
    id: 22,
    legalName: 'Farmácia e Drogaria S.A.',
    socialName: null,
    description: null,
    logoUrl: null,
    city: 'Salvador',
    state: 'BA',
  },
  {
    id: 23,
    legalName: 'Consultoria Ambiental LTDA',
    socialName: 'EcoConsult',
    description: 'Assessoria em conformidade ambiental',
    logoUrl: 'https://picsum.photos/seed/company23/64/64',
    city: 'Curitiba',
    state: 'PR',
  },
  {
    id: 24,
    legalName: 'Móveis e Decoração LTDA',
    socialName: 'DécorLux',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company24/64/64',
    city: 'Porto Alegre',
    state: 'RS',
  },
  {
    id: 25,
    legalName: 'Infraestrutura de TI S.A.',
    socialName: null,
    description: 'Data center e infraestrutura cloud',
    logoUrl: null,
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 26,
    legalName: 'Confecções Industriais LTDA',
    socialName: 'InduConfec',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company26/64/64',
    city: null,
    state: 'SC',
  },
  {
    id: 27,
    legalName: 'Consultoria Jurídica Premium S.A.',
    socialName: 'LegalPro',
    description: 'Advocacia especializada em corporativo',
    logoUrl: 'https://picsum.photos/seed/company27/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 28,
    legalName: 'Impressão e Gráfica LTDA',
    socialName: null,
    description: null,
    logoUrl: null,
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 29,
    legalName: 'Limpeza Industrial Especializada LTDA',
    socialName: 'IndClean',
    description: 'Limpeza pesada e desinfecção',
    logoUrl: 'https://picsum.photos/seed/company29/64/64',
    city: 'Manaus',
    state: 'AM',
  },
  {
    id: 30,
    legalName: 'Publicidade e Marketing Digital S.A.',
    socialName: null,
    description: 'Estratégias de marketing e branding',
    logoUrl: 'https://picsum.photos/seed/company30/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 31,
    legalName: 'Soluções em Ar Condicionado LTDA',
    socialName: 'ClimaSol',
    description: null,
    logoUrl: null,
    city: null,
    state: null,
  },
  {
    id: 32,
    legalName: 'Equipamentos Eletrônicos S.A.',
    socialName: 'ElectroTech',
    description: 'Distribuidora de eletrônicos profissionais',
    logoUrl: 'https://picsum.photos/seed/company32/64/64',
    city: 'Belo Horizonte',
    state: 'MG',
  },
  {
    id: 33,
    legalName: 'Processamento de Alimentos LTDA',
    socialName: null,
    description: null,
    logoUrl: 'https://picsum.photos/seed/company33/64/64',
    city: 'Campinas',
    state: 'SP',
  },
  {
    id: 34,
    legalName: 'Estacionamentos e Garagens S.A.',
    socialName: 'ParkGarage',
    description: 'Gestão de estacionamentos inteligentes',
    logoUrl: null,
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 35,
    legalName: 'Telecomunicações Inovadora LTDA',
    socialName: null,
    description: 'Serviços de conectividade empresarial',
    logoUrl: 'https://picsum.photos/seed/company35/64/64',
    city: 'Brasília',
    state: 'DF',
  },
  {
    id: 36,
    legalName: 'Serviços de Contabilidade Premium LTDA',
    socialName: 'ContaMax',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company36/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 37,
    legalName: 'Bebidas e Alimentos Naturais S.A.',
    socialName: null,
    description: 'Produtos orgânicos e sustentáveis',
    logoUrl: null,
    city: null,
    state: 'RS',
  },
  {
    id: 38,
    legalName: 'Consultoria de Processos LTDA',
    socialName: 'ProcessOptim',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company38/64/64',
    city: 'Curitiba',
    state: 'PR',
  },
  {
    id: 39,
    legalName: 'Indústria de Plásticos LTDA',
    socialName: null,
    description: 'Manufatura de componentes em plástico',
    logoUrl: null,
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 40,
    legalName: 'Gestão de Eventos e Conferências S.A.',
    socialName: 'EventsPro',
    description: 'Organização de eventos corporativos',
    logoUrl: 'https://picsum.photos/seed/company40/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 41,
    legalName: 'Metalurgia e Siderurgia LTDA',
    socialName: null,
    description: null,
    logoUrl: 'https://picsum.photos/seed/company41/64/64',
    city: 'Belo Horizonte',
    state: 'MG',
  },
  {
    id: 42,
    legalName: 'Educação Corporativa Inovadora LTDA',
    socialName: 'CorpLearn',
    description: 'Treinamento e desenvolvimento de talentos',
    logoUrl: null,
    city: null,
    state: null,
  },
  {
    id: 43,
    legalName: 'Seguros e Proteção Financeira S.A.',
    socialName: null,
    description: null,
    logoUrl: 'https://picsum.photos/seed/company43/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 44,
    legalName: 'Instalação de Piscinas LTDA',
    socialName: 'PoolInstall',
    description: 'Projetos e instalação de piscinas',
    logoUrl: 'https://picsum.photos/seed/company44/64/64',
    city: 'Salvador',
    state: 'BA',
  },
  {
    id: 45,
    legalName: 'Desenvolvimento de Software Avançado S.A.',
    socialName: null,
    description: 'Desenvolvimento customizado e consultoria tech',
    logoUrl: null,
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 46,
    legalName: 'Artigos de Esportes e Fitness LTDA',
    socialName: 'SportGear',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company46/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 47,
    legalName: 'Consultoria de Supply Chain LTDA',
    socialName: null,
    description: 'Otimização de cadeias de suprimento',
    logoUrl: null,
    city: null,
    state: 'SP',
  },
  {
    id: 48,
    legalName: 'Sistemas de Pagamento Digital S.A.',
    socialName: 'PaySys',
    description: null,
    logoUrl: 'https://picsum.photos/seed/company48/64/64',
    city: 'Curitiba',
    state: 'PR',
  },
  {
    id: 49,
    legalName: 'Tintas e Vernizes Industriais LTDA',
    socialName: null,
    description: 'Produtos para proteção e acabamento',
    logoUrl: 'https://picsum.photos/seed/company49/64/64',
    city: 'Porto Alegre',
    state: 'RS',
  },
  {
    id: 50,
    legalName: 'Locação de Equipamentos LTDA',
    socialName: 'EquipRent',
    description: null,
    logoUrl: null,
    city: 'Brasília',
    state: 'DF',
  },
  {
    id: 51,
    legalName: 'Consultoria em Inovação S.A.',
    socialName: null,
    description: 'Estratégia de inovação empresarial',
    logoUrl: 'https://picsum.photos/seed/company51/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 52,
    legalName: 'Vidraçaria Comercial LTDA',
    socialName: 'GlassComm',
    description: null,
    logoUrl: null,
    city: null,
    state: null,
  },
  {
    id: 53,
    legalName: 'Consultoria em Compliance LTDA',
    socialName: null,
    description: 'Auditoria e conformidade regulatória',
    logoUrl: 'https://picsum.photos/seed/company53/64/64',
    city: 'Rio de Janeiro',
    state: 'RJ',
  },
  {
    id: 54,
    legalName: 'Usina de Açúcar e Álcool S.A.',
    socialName: null,
    description: null,
    logoUrl: null,
    city: 'Ribeirão Preto',
    state: 'SP',
  },
  {
    id: 55,
    legalName: 'Consultoria em Branded Content LTDA',
    socialName: 'BrandStory',
    description: 'Produção de conteúdo estratégico',
    logoUrl: 'https://picsum.photos/seed/company55/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 56,
    legalName: 'Pecuária e Produção Animal LTDA',
    socialName: null,
    description: null,
    logoUrl: 'https://picsum.photos/seed/company56/64/64',
    city: null,
    state: 'MT',
  },
  {
    id: 57,
    legalName: 'Geração de Energia Térmica S.A.',
    socialName: 'ThermoEnergy',
    description: 'Usinas termelétricas e cogeração',
    logoUrl: null,
    city: 'Poços de Caldas',
    state: 'MG',
  },
  {
    id: 58,
    legalName: 'Consultoria em Inteligência Artificial LTDA',
    socialName: null,
    description: null,
    logoUrl: 'https://picsum.photos/seed/company58/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
  {
    id: 59,
    legalName: 'Indústria Cervejeira Artesanal LTDA',
    socialName: 'BrewCraft',
    description: 'Fabricação de cervejas especiais',
    logoUrl: null,
    city: null,
    state: null,
  },
  {
    id: 60,
    legalName: 'Consultoria em ESG e Sustentabilidade S.A.',
    socialName: null,
    description: 'Estratégia de governança sustentável',
    logoUrl: 'https://picsum.photos/seed/company60/64/64',
    city: 'São Paulo',
    state: 'SP',
  },
]

export function mockFetchCompaniesForNpo(params: { page?: number; size?: number } = {}): PageResponse<CompanyListItem> {
  const page = params.page ?? 0
  const size = params.size ?? 10
  const totalElements = MOCK_COMPANIES.length
  const totalPages = Math.ceil(totalElements / size)
  const start = page * size
  const content = MOCK_COMPANIES.slice(start, start + size)
  return {
    content,
    totalElements,
    totalPages,
    number: page,
    size,
    first: page === 0,
    last: page >= totalPages - 1,
  }
}
