name: Discord PR Notifier

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }} 
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }} 
          color: "#4834d4"
          username: "GitHub PR Bot"
          message: |
            **Novo Pull Request Aberto!**
            **Título:** ${{ github.event.pull_request.title }}
            **Autor:** ${{ github.event.pull_request.user.login }}
            **Link:** ${{ github.event.pull_request.html_url }}