name: Sync to GitLab

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
      - dev

jobs:
  sync:
    name: Sync to GitLab
    runs-on: ubuntu-latest
    
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push para o GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: "tools.ages.pucrs.br/vinculo-hub/vinculohub.git" 
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@$GITLAB_REPO
          git push gitlab HEAD:${{ github.base_ref || github.ref_name }} --force